### PR TITLE
Initial implementation of TreeList<T>

### LINKED ISSUE #6: Support for List<T> equivalent
* Interfaces (omits inherited interfaces)
  * `System.Collections.Generic.IList<T>`
  * `System.Collections.Generic.IReadOnlyList<T>`
  * `System.Collections.IList`
* Special considerations
  * `System.Converter<TInput, TOutput>` is not available prior to .NET Standard 2.0, so the `ConvertAll<TOutput>` method is implemented using `Func<T, TOutput>`
  * ⚠️ The `TreeList<T>(int)` and `List<T>(int)` constructors have the same signature, but *very* different behavior. Users switching to this library may be mistake-prone if they were previously creating lists with known capacities.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #6

### CODE REVIEW

**Comment by MkazemAkhgary** [comment]
Fantastic! 

This sounds good. I may actually make adopted version of this. The collection has to be sorted and stable. 

The collection that i need should accept duplicate keys, and by stable sort items with same key has same order as they were added.

Such collection does not exist in. Net and we have to flesh out this collection implementation.

Im also interested in making variant, subset collections of BTree. This could be useful but my aim is for first collection that i mentioned.

In few days i may create pull request with new changes. Though ill have to see how this goes. It needs a testing certainly.

**Comment by MkazemAkhgary** [comment]
since I'm focusing on other project, I had other things at priority. ive found this 

https://github.com/sestoft/C5

It has great set of collection and its also being maintained.

**Comment by sharwell** [comment]
@MkazemAkhgary Those are definitely interesting. Do keep in mind that the tree data structures in that collection are binary trees, as opposed to the B+-trees used here.

**Comment by sharwell** [comment]
Some general thoughts after working on this type for quite a while now:

### Advantages of B+-trees

The main advantages of B+-trees are the following:

* **Improved worst-case allocation behavior.** While `List<T>` offers amortized O(1) insertions, the worst case single insertion is O(n). `TreeList<T>` offers worst-case insertion of O(log n).
* **Avoiding the large object heap (LOH).** The segmentation of `TreeList<T>` into pages ensures that the large object heap is not used by this implementation provided `new T[branchingFactor]` does not exceed the LOH threshold.
* **Reduced sensitivity to fragmentation.** For the same reasons as the previous, `TreeList<T>` is much less sensitive to memory fragmentation, which can be especially relevant when executing within a 32-bit process.

### Summary of adopting `TreeList<T>` over `List<T>`

While `TreeList<T>` is generally a drop-in replacement for `List<T>`, there are important differences to remember.

* The `TreeList<T>(int)` constructor is *very* different from the `List<T>(int)` constructor. I'm not sure what the best way to resolve this is - possibly an analyzer which reports a warning when the `TreeList<T>(int)` constructor is used without named arguments?
* `TreeList<T>` has the same concurrency requirements as `List<T>` - they are only safe for unprotected access on multiple threads when no writers are involved. However, due to the increased internal complexity, `TreeList<T>` is more likely to exhibit highly unpredictable behavior in cases where the concurrency rules are violated.

**Pull request merged**
